app.name=MedControl
server.port=8087

spring.datasource.url=jdbc:postgresql://localhost:5432/project_showcase
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.web=INFO
logging.level.org.medcontrol=INFO
logging.level.org.springframework.security=INFO

spring.rabbitmq.host=rabbitmq-medcontrol
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.security.user.name=user
spring.security.user.password=password

vapid.public-key=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEgQDVmIJvKOkHcXo6uMxL3z_uZjEE2QjQvHNTFiasFKNOO0ByIVyRMsbIAhFzu8Jd_iCWqxvGSwfxyfxBJYYOsg
vapid.private-key=MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgEydt0JFdxPXDtTG9k_pjnmFD5g6rYfOSwkzEQAJPiZSgCgYIKoZIzj0DAQehRANCAASBANWYgm8o6Qdxejq4zEvfP-5mMQTZCNC8c1MWJqwUo047QHIhXJEyxsgCEXO7wl3-IJarG8ZLB_HJ_EElhg6y
vapid.public-key-raw=BIEA1ZiCbyjpB3F6OrjMS98_7mYxBNkI0LxzUxYmrBSjTjtAciFckTLGyAIRc7vCXf4glqsbxksH8cn8QSWGDrI