
services:
  postgres:
    image: postgres:latest
    container_name: postgres-medcontrol
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "project_showcase"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - monitoring
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-medcontrol
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - monitoring
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-medcontrol
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - monitoring
    depends_on:
      postgres:
        condition: service_healthy

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: logstash-medcontrol
    volumes:
      - ./logstash-medcontrol.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/var/log/medcontrol
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - monitoring
    depends_on:
      postgres:
        condition: service_healthy
      loki:
        condition: service_started
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  loki:
    image: grafana/loki:2.9.0
    container_name: loki-medcontrol
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-medcontrol
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - loki
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-medcontrol
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - monitoring
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  medcontrol-app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: medcontrol-app
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-medcontrol:5432/project_showcase
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATA_REDIS_HOST=redis-medcontrol
      - SPRING_RABBITMQ_HOST=rabbitmq-medcontrol
    networks:
      - monitoring
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
  pgadmin_data:
  grafana_data:
  prometheus_data:
