input {
  file {
    path => "/var/log/medcontrol/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "medcontrol-app"
  }
}

filter {
  if [type] == "medcontrol-app" {
    
    mutate {
      add_field => { "application" => "medcontrol" }
      add_field => { "environment" => "dev" }
    }
  }
}

output {
  loki {
    url => "http://loki:3100/loki/api/v1/push"
    batch_size => 100
    codec => json
  }
}